name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13-dev"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
        django-version:
          - "5.0"
          - "4.2"
        exclude:
          - django-version: "5.0"
            python-version: "3.9"
    name: Python ${{ matrix.python-version }} & Django ${{ matrix.django-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: astral-sh/setup-uv@v2
    - run: uv run tox -e py${{ matrix.python-version }}-django${{ matrix.django-version }}
