name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8.3', '3.7.8', '3.6.11']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Black
      run: poetry run black .
    - name: Tox 3.8
      if: ${{ matrix.python-version  == '3.8.3' }}
      run: poetry run tox -e 'py38-django{2,3}'
    - name: Tox 3.7
      if: ${{ matrix.python-version  == '3.7.8' }}
      run: poetry run tox -e 'py37-django{2,3}'
    - name: Tox 3.6
      if: ${{ matrix.python-version  == '3.6.11' }}
      run: poetry run tox -e 'py36-django{2,3}'
