name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.12
          - 3.11
          - 3.10
          - 3.9
        django-version:
          - 5.0
          - 4.2
          - 3.2
        exclude:
          - django-version: 3.2
            python-version: 3.10
          - django-version: 3.2
            python-version: 3.11
          - django-version: 3.2
            python-version: 3.12
          - django-version: 4.2
            python-version: 3.11
          - django-version: 4.2
            python-version: 3.12
          - django-version: 5.0
            python-version: 3.9
    name: Python ${{ matrix.python-version }} & Django ${{ matrix.django-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        python -m venv .venv/
        .venv/bin/pip install poetry
    - name: Install dependencies
      run: |
        .venv/bin/pip install --upgrade pip
        .venv/bin/poetry install
    - name: Run tox
      run: .venv/bin/poetry run tox -e py${{ matrix.python-version }}-django${{ matrix.django-version }}
